<hr>

<h2 style = "font-family:times; text-align: center;"> Creating an Database for Many to Many Relatioships </h2>

<hr>

<div style = "border: 2px solid black; padding: 10px; color: black; background-color: white;text-align: center; vertical-align:middle; font-family:times;">
    <h4> Creating an database to track courses participants </h4>
</div>

<hr>

In [8]:
import json
import sqlite3

conn = sqlite3.connect('rosterdb.sqlite')
cur = conn.cursor()

# Drop table if exists, create a new one
cur.executescript('''
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Member;
DROP TABLE IF EXISTS Course;

CREATE TABLE User (
    id     INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name   TEXT UNIQUE
);

CREATE TABLE Course (
    id     INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    title  TEXT UNIQUE
);

CREATE TABLE Member (
    user_id     INTEGER,
    course_id   INTEGER,
    role        INTEGER,
    PRIMARY KEY (user_id, course_id)
)
''')

fname = input('Enter file name: ')
if len(fname) < 1:
    fname = 'roster_data.json'

# Data format after the json.loads():    
#   [ "Charley", "si110", 1 ],
#   [ "Mea", "si110", 0 ],
str_data = open(fname).read()
json_data = json.loads(str_data)

for entry in json_data:

    name = entry[0]
    title = entry[1]
    role = entry[2]

    print((name, title, role))

    # Insert new names into Users
    cur.execute('''
            INSERT OR IGNORE INTO User (name) VALUES ( ? )
                ''', ( name, ) )
    
    # Take the previous inserted user id to place into Member table
    cur.execute('SELECT id FROM User WHERE name = ? ', (name, ))
    user_id = cur.fetchone()[0]

    cur.execute('''
            INSERT OR IGNORE INTO Course (title) VALUES ( ? )
                ''', ( title, ) )
    
    cur.execute('SELECT id FROM Course WHERE title = ? ', (title, ))
    course_id = cur.fetchone()[0]

    cur.execute('''
            INSERT OR REPLACE INTO Member (user_id, course_id, role) VALUES ( ?, ?, ?)
                ''', ( user_id, course_id, role) )

    conn.commit()

Enter file name:

('Naomie', 'si110', 1)
('Marwan', 'si110', 0)
('Cade', 'si110', 0)
('Simon', 'si110', 0)
('Aieecia', 'si110', 0)
('Cassy', 'si110', 0)
('Darryl', 'si110', 0)
('Khalan', 'si110', 0)
('Rhiona', 'si110', 0)
('Idun', 'si110', 0)
('Rayna', 'si110', 0)
('Mehek', 'si110', 0)
('Kaiwen', 'si110', 0)
('Makaila', 'si110', 0)
('Eris', 'si110', 0)
('Aazaan', 'si110', 0)
('Jura', 'si110', 0)
('Ifunanya', 'si110', 0)
('Annalise', 'si110', 0)
('Ceirin', 'si110', 0)
('Filip', 'si106', 1)
('Natasha', 'si106', 0)
('Madisen', 'si106', 0)
('Zeek', 'si106', 0)
('Siena', 'si106', 0)
('Digby', 'si106', 0)
('Marko', 'si106', 0)
('Loui', 'si106', 0)
('Karla', 'si106', 0)
('MacCartney', 'si106', 0)
('Elisabetta', 'si106', 0)
('Bushra', 'si106', 0)
('Tyrnan', 'si106', 0)
('Ayleen', 'si106', 0)
('Chrissie', 'si106', 0)
('Ines', 'si106', 0)
('Teo', 'si106', 0)
('Rianne', 'si106', 0)
('Katharine', 'si106', 0)
('Maksim', 'si106', 0)
('Rihan', 'si106', 0)
('Vicki', 'si106', 0)
('Rosea', 'si106', 0)
('Kristal', 'si106', 0)
('Tiarn', 'si106', 0)
('Anika', 'si106', 0)
('Umer', 'si106', 0)
('Kaysie', 'si106', 0)
('Muireann', 'si106', 0)
('Yuri', 'si106', 0)
('Aldred', 'si106', 0)
('Jema', 'si106', 0)
('Reiss', 'si106', 0)
('Tomas', 'si106', 0)
('Ekhlass', 'si106', 0)
('Callie', 'si106', 0)
('Mikee', 'si106', 0)
('Sanjay', 'si106', 0)
('Eesa', 'si106', 0)
('Sylvana', 'si106', 0)
('Duaa', 'si106', 0)
('Derri', 'si106', 0)
('Steve', 'si106', 0)
('Gil', 'si106', 0)
('Kaiwen', 'si106', 0)
('Idahosa', 'si106', 0)
('Diane', 'si106', 0)
('Aseel', 'si106', 0)
('Carrick', 'si206', 1)
('Declain', 'si206', 0)
('Jessamy', 'si206', 0)
('Harley', 'si206', 0)
('Jean', 'si206', 0)
('Chester', 'si206', 0)
('Nerisse', 'si206', 0)
('Tanasha', 'si206', 0)
('Jaosha', 'si206', 0)
('Nyah', 'si206', 0)
('Narissa', 'si206', 0)
('Yu', 'si206', 0)
('Alaska', 'si206', 0)
('Maeghan', 'si206', 0)
('Derren', 'si206', 0)
('Aydin', 'si206', 0)
('Christy', 'si206', 0)
('Kaydence', 'si206', 0)
('Blyth', 'si206', 0)
('Kiya', 'si206', 0)
('Karima', 'si206', 0)
('Oakley', 'si301', 1)
('Kasim', 'si301', 0)
('Jeanna', 'si301', 0)
('Kye', 'si301', 0)
('Malachi', 'si301', 0)
('Munachi', 'si301', 0)
('Annabella', 'si301', 0)
('Maximilian', 'si301', 0)
('Ayleigh', 'si301', 0)
('Kya', 'si301', 0)
('Fizzah', 'si301', 0)
('Jomana', 'si301', 0)
('Amani', 'si301', 0)
('Roger', 'si301', 0)
('Karmyn', 'si301', 0)
('Darwyn', 'si301', 0)
('Loudon', 'si301', 0)
('Katy', 'si301', 0)
('Trinity', 'si301', 0)
('Kenzie', 'si301', 0)
('Benjamin', 'si301', 0)
('Lianna', 'si301', 0)
('Stewart', 'si301', 0)
('Caileen', 'si301', 0)
('Aryn', 'si301', 0)
('Tianna', 'si310', 1)
('Etiene', 'si310', 0)
('Steffie', 'si310', 0)
('Alfred', 'si310', 0)
('Konan', 'si310', 0)
('Jillian', 'si310', 0)
('Sadie', 'si310', 0)
('Lexy', 'si310', 0)
('Ashwin', 'si310', 0)
('Zuzia', 'si310', 0)
('Aarez', 'si310', 0)
('Jostelle', 'si310', 0)
('Broghan', 'si310', 0)
('Manolo', 'si310', 0)
('Angela', 'si310', 0)
('Brunon', 'si310', 0)
('Yusef', 'si310', 0)
('Melodie', 'si310', 0)
('Shalamar', 'si310', 0)
('Danial', 'si310', 0)
('Lacey', 'si310', 0)
('Brookelyn', 'si310', 0)
('Jingyi', 'si310', 0)
('Wallace', 'si310', 0)
('Aleah', 'si310', 0)
('Effie', 'si310', 0)
('Shay', 'si310', 0)
('Raniyah', 'si310', 0)
('Darcie', 'si310', 0)
('Jenni', 'si310', 0)
('Malebo', 'si310', 0)
('Orlanna', 'si310', 0)
('Amrit', 'si310', 0)
('Zishan', 'si310', 0)
('Bonni', 'si310', 0)
('Louis', 'si310', 0)
('Murdina', 'si310', 0)
('Ailey', 'si310', 0)
('AJ', 'si310', 0)
('Zakariya', 'si310', 0)
('Aimie', 'si310', 0)
('Sandy', 'si310', 0)
('Kennedi', 'si334', 1)
('Rebeca', 'si334', 0)
('Roni', 'si334', 0)
('Oluwatobiloba', 'si334', 0)
('Shane', 'si334', 0)
('Imogen', 'si334', 0)
('Nadisa', 'si334', 0)
('Anona', 'si334', 0)
('Dareh', 'si334', 0)
('Qainat', 'si334', 0)
('Dhara', 'si334', 0)
('Lotus', 'si334', 0)
('Athon', 'si334', 0)
('Ramone', 'si334', 0)
('Xavier', 'si334', 0)
('Kellyanne', 'si334', 0)
('Brendon', 'si334', 0)
('Kiyonari', 'si334', 0)
('Faheem', 'si334', 0)
('Queeneffa', 'si334', 0)
('Malachai', 'si334', 0)
('Nihaal', 'si334', 0)
('Serene', 'si334', 0)
('Lorelei', 'si334', 0)
('Hussain', 'si334', 0)
('Usman', 'si334', 0)
('Balian', 'si334', 0)
('Kashuf', 'si334', 0)
('Sabriyah', 'si334', 0)
('Lukasz', 'si363', 1)
('Dennan', 'si363', 0)
('Joanna', 'si363', 0)
('Macy', 'si363', 0)
('Aamna', 'si363', 0)
('Lusiana', 'si363', 0)
('Leland', 'si363', 0)
('Pawel', 'si363', 0)
('Ruairi', 'si363', 0)
('Kalani', 'si363', 0)
('Rayyan', 'si363', 0)
('Johannes', 'si363', 0)
('Courteney', 'si363', 0)
('Jules', 'si363', 0)
('Aseel', 'si363', 0)
('Tione', 'si363', 0)
('Sandy', 'si363', 0)
('Diya', 'si363', 0)
('Harish', 'si363', 0)
('Caolain', 'si363', 0)
('Muhammed', 'si363', 0)
('Sairah', 'si363', 0)
('Soul', 'si363', 0)
('Alanas', 'si363', 0)
('Fauzaan', 'si363', 0)
('Kensey', 'si363', 0)
('Yva', 'si363', 0)
('Zayne', 'si363', 0)
('Alihaider', 'si363', 0)
('Keith', 'si363', 0)
('Courtny', 'si363', 0)
('Zinto', 'si363', 0)
('Stanislaw', 'si363', 0)
('Griffyn', 'si363', 0)
('Tieran', 'si363', 0)
('Ze', 'si363', 0)
('Yorgos', 'si363', 0)
('Tanith', 'si363', 0)
('Keely', 'si363', 0)
('Allegria', 'si363', 0)
('Badsha', 'si363', 0)
('Amieleigh', 'si363', 0)
('Alyshia', 'si363', 0)
('Liliana', 'si363', 0)
('Meledy', 'si364', 1)
('Alona', 'si364', 0)
('Aishah', 'si364', 0)
('Toby', 'si364', 0)
('Alan', 'si364', 0)
('Johnson', 'si364', 0)
('Dua', 'si364', 0)
('Qasim', 'si364', 0)
('Brody', 'si364', 0)
('Si', 'si364', 0)
('Franciszek', 'si364', 0)
('Raymond', 'si364', 0)
('Micah', 'si364', 0)
('Denhi', 'si364', 0)
('Victoria', 'si364', 0)
('Eni', 'si364', 0)
('Timucin', 'si364', 0)
('Teigon', 'si364', 0)
('Kasha', 'si364', 0)
('Muhsin', 'si364', 0)
('Jaymie', 'si364', 0)
('Rhy', 'si364', 0)
('Alistar', 'si364', 0)
('Anaya', 'si364', 0)
('Jeyun', 'si364', 0)
('Fendi', 'si364', 0)
('Eoghain', 'si364', 0)
('Ioannis', 'si364', 0)
('Jez', 'si364', 0)
('Janna', 'si364', 0)
('Almaas', 'si364', 0)
('Elliana', 'si364', 0)
('Blythe', 'si364', 0)
('Lance', 'si364', 0)
('Warren', 'si364', 0)
('Aleina', 'si364', 0)
('Santino', 'si364', 0)
('Rayden', 'si364', 0)
('Caity', 'si364', 0)
('Tylar', 'si422', 1)
('Sambrid', 'si422', 0)
('Kaleb', 'si422', 0)
('Palmer', 'si422', 0)
('Ashlyn', 'si422', 0)
('Tyrone', 'si422', 0)
('Caiden', 'si422', 0)
('Andrea', 'si422', 0)
('Xanthia', 'si422', 0)
('Jewel', 'si422', 0)
('Ewan', 'si422', 0)
('Tara', 'si422', 0)
('Ben', 'si422', 0)
('Eliane', 'si422', 0)
('Marybeth', 'si422', 0)
('Keemaya', 'si422', 0)
('Santino', 'si422', 0)
('Maykayla', 'si422', 0)
('Franciszek', 'si422', 0)
('Laia', 'si430', 1)
('Pearce', 'si430', 0)
('Macaulay', 'si430', 0)
('Kealon', 'si430', 0)
('Kadyn', 'si430', 0)
('Monique', 'si430', 0)
('Dyllan', 'si430', 0)
('Ibraheem', 'si430', 0)
('Colin', 'si430', 0)
('Solomon', 'si430', 0)
('Kadyleigh', 'si430', 0)
('Loche', 'si430', 0)
('Taiba', 'si430', 0)
('Kenan', 'si430', 0)
('Keera', 'si430', 0)
('Marwad', 'si430', 0)
('Carra', 'si430', 0)
('Evelyn', 'si430', 0)
('Havila', 'si430', 0)
('Isabell', 'si430', 0)
('Hillary', 'si430', 0)
('Tiarn', 'si430', 0)
('Aiyana', 'si430', 0)
('Leyton', 'si430', 0)
('Blythe', 'si430', 0)
('Sommer', 'si430', 0)
('Caitlinn', 'si430', 0)
('Becky', 'si430', 0)
('Insiya', 'si430', 0)
('Callin', 'si430', 0)
('Kimi', 'si430', 0)
('Zaya', 'si430', 0)
('Beatriz', 'si430', 0)
('Daood', 'si430', 0)
('Juanita', 'si430', 0)
('Momina', 'si430', 0)
('Cliodhna', 'si430', 0)
('Celsea', 'si430', 0)
('Lexy', 'si430', 0)
('Johnpaul', 'si430', 0)
('Blaine', 'si430', 0)
('Savannah', 'si430', 0)
('Aiesha', 'si430', 0)

In [10]:
sqlstr = '''
            SELECT User.name,Course.title, Member.role  
            FROM User JOIN Member JOIN Course 
            ON User.id = Member.user_id AND Member.course_id = Course.id
            ORDER BY User.name DESC, Course.title DESC, Member.role DESC LIMIT 2 '''

for row in cur.execute(sqlstr):
    print(str(row[0]), " | ", str(row[1]), " | ", str(row[2]))
    
cur.close()

Zuzia  |  si310  |  0
Zishan  |  si310  |  0

<hr>